version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "icon-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bbmfc1qevpsk"
s3_prefix = "icon-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"websockets-connections\""

